package com.example.customerservice;

import javax.jws.WebService;

/**
 * This class was generated by Apache CXF 2.3.0
 * Wed Jan 26 14:07:03 CST 2011
 * Generated source version: 2.3.0
 * 
 */
 
@WebService
public interface CustomerService {

    public java.util.List<Customer> getCustomersByName(
        java.lang.String name
    ) ;
}
